GesturAuth/GesturAuth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^leap/', include('leap.urls')),
    url(r'^admin/', admin.site.urls),
]

GesturAuth/leap/urls.py
from django.conf.urls import url

from . import views

app_name = 'leap'
urlpatterns = [
    url(r'^signupform/$', views.signupform, name='signupform'),
    url(r'^$', views.SignupView.as_view(), name='signup'),
    url(r'^authentication/$', views.authentication, name='authentication'),
]

GesturAuth/leap/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
# Create your models here.

@python_2_unicode_compatible  # only if you need to support Python 2
class User(models.Model):
    username = models.CharField(max_length=100)

    def __str__(self):
        return self.username

    class Meta:
        ordering = ['id']

GesturAuth/leap/forms.py
from django import forms
from .models import User

class SignupForm(forms.ModelForm):
    Username = forms.CharField(label='Username', max_length=100)
    class Meta:
        model = User
        fields = []

GesturAuth/leap/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import User
from .forms import SignupForm



class SignupView(generic.FormView):
    template_name = 'leap/signup.html'
    form_class = SignupForm

    def get_context_data(self, **kwargs):
        context = super(SignupView, self).get_context_data(**kwargs)
        # context['user'] = User.objects.get(pk=int(self.kwargs['pk']))
        return context

    def form_valid(self, form):
        return super(SignupView, self).form_valid(form)

def signupform(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username_val = form.cleaned_data['Username']
            user = User(username=username_val)
            user.save()
            user_id = user.id
            return HttpResponseRedirect(reverse('leap:authentication', args=(user_id, )))
    else:
        form = SignupForm()
    return render(request, 'leap/signup.html', {'form':form});

class AuthenticationView(generic.DetailView):
    template_name = 'leap/authentication.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super(AuthenticationView, self).get_context_data(**kwargs)
        return context

GesturAuth/leap/templates/leap/authentication.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

Instructions:

Leap Motion Stuff for {{ user }}

GesturAuth/leap/templates/leap/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'leap:authentication' question.id %}">Vote again?</a>

GesturAuth/leap/templates/leap/signup.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'leap/style.css' %}" />

<h1>
  Signup Form
</h1>

<form action="{% url 'leap:signupform' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Start LeapMotion Authorization" />
</form>